name: "Mypy"
on:
  pull_request:

jobs:
  run_mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run Mypy
        uses: jashparekh/mypy-action@v2
        with:
          path: '.'
          version: 'latest'
          mypy_flags: '--verbose'
          mypy_config_file: 'mypy.ini'
          requirement_files: 'requirements.dev.txt'
